[pytest]
addopts = -v -s --alluredir test_results/allure-results --clean-alluredir

markers =
    api: mark a test as an API test.
    ui: mark a test as a UI test.
    critical: mark a test as critical.
    e2e: mark a test as end-to-end.
